### ISSUE TITLE
jw.ruc.edu.cn cookies are invalid

### ISSUE THREAD

**Issue by timturing** [panjd123/ruclogin#6]
按照配置进行后，现版本结果token会返回`'access_token': 'deleted'`，导致后续的`jw.ruc.edu.cn cookies are invalid`和`Login failed`

**Comment by panjd123** [comment]
我的测试没有复现这个问题，我观察到这几天 https://ruccourse.panjd.net/ 的访问量很高，而且有大量的 success 请求增加，我猜测这个问题应该不普遍。
